# SPDX-FileCopyrightText: 2025 The vita49-rs Authors
#
# SPDX-License-Identifier: MIT OR Apache-2.0
---
policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      dco: true
      spellcheck:
        locale: US
      conventional:
        types:
          - chore
          - docs
          - perf
          - refactor
          - style
          - test
          - release
        scopes:
          - .*
        descriptionLength: 72
