# SPDX-FileCopyrightText: 2025 Valley Tech Systems, Inc
#
# SPDX-License-Identifier: MIT OR Apache-2.0
---
name: ci
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # We need a very new version of Wireshark for these tests, so just
  # skip them for now.
  SKIP_WIRESHARK_TESTS: true

# By default, only give actions read access.
permissions: read-all

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Rust
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy,rustfmt
      - name: Run build
        run: cargo build --all-features
      - name: Run tests
        run: cargo test --all-features
      - name: Run doc build
        run: cargo doc --all-features
      - name: Run clippy
        run: cargo clippy --all-features -- -Dwarnings
      - name: Run rustfmt
        run: cargo fmt --check

  reuse:
    name: Reuse compliance
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542

  commit_check:
    name: Commit check
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Conform
        run: >
          docker run
          --rm
          -v "$PWD:/src:ro,Z"
          -w /src
          ghcr.io/siderolabs/conform:v0.1.0-alpha.30
          enforce
          --base-branch=origin/main

  msrv:
    name: Check MSRV
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Rust
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: 1.71.0
      - name: Run build
        run: cargo build --all-features --package vita49
